// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFZ8PL-SlddCJsZ5krExK_z2qqUfPtlrs',
    appId: '1:662441837073:web:ddd912d0e422740bd367b0',
    messagingSenderId: '662441837073',
    projectId: 'heka-bfb34',
    authDomain: 'heka-bfb34.firebaseapp.com',
    storageBucket: 'heka-bfb34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnaBvOJFQKzA4CegFfBwByNtd0SHk0xVU',
    appId: '1:662441837073:android:3a77453328569769d367b0',
    messagingSenderId: '662441837073',
    projectId: 'heka-bfb34',
    storageBucket: 'heka-bfb34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsnEDgh0SZUhFm5bIhTZ1SbEaf_qL5tI',
    appId: '1:662441837073:ios:594d93929feabad3d367b0',
    messagingSenderId: '662441837073',
    projectId: 'heka-bfb34',
    storageBucket: 'heka-bfb34.firebasestorage.app',
    iosBundleId: 'com.example.hekaStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEsnEDgh0SZUhFm5bIhTZ1SbEaf_qL5tI',
    appId: '1:662441837073:ios:594d93929feabad3d367b0',
    messagingSenderId: '662441837073',
    projectId: 'heka-bfb34',
    storageBucket: 'heka-bfb34.firebasestorage.app',
    iosBundleId: 'com.example.hekaStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFZ8PL-SlddCJsZ5krExK_z2qqUfPtlrs',
    appId: '1:662441837073:web:9afeb8fdbd42e6a9d367b0',
    messagingSenderId: '662441837073',
    projectId: 'heka-bfb34',
    authDomain: 'heka-bfb34.firebaseapp.com',
    storageBucket: 'heka-bfb34.firebasestorage.app',
  );
}
